version:  1.0.2
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=yourpassword
      - MYSQL_DATABASE=a
    ports:
      - "3306:3306"
volumes:
  db_data:
