version:  1.0.2

services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    network_mode: "host"  


volumes:
  db_data:
