version:  1.0.2

services:
  db:
    image: mysql:latest
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mana123
      - MYSQL_DATABASE=a
    ports:
      - "3306:3306"

  app:
    build: .
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:
