version:  1.0.2

services:
  app:
    container_name: nodejs_terminal_app
    build: .
    depends_on:
      - db
    networks:
      - app-network

  db:
    container_name: mysql_db
    image: mysql
    environment:
      MYSQL_DATABASE: 'aaa'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
