version:  1.0.2

services:
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=yourpassword
      - MYSQL_DATABASE=yourdatabase
    ports:
      - "3306:3306"

  app:
    image: your-app-image
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=mana123
      - DATABASE_NAME=a

volumes:
  db_data:
