version:  1.0.2

services:
  app:
    container_name: nodejs_terminal_app
    build: .
    depends_on:
      - db
    networks:
      - app-network

  db:
    container_name: mysql_db
    image: mysql:8.0.30
    environment:
      MYSQL_DATABASE: 'a'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: ''
      MYSQL_ROOT_PASSWORD: ''
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
